-- Lux Knowledge Platform Database Schema
-- SQLite 3 with strict typing
--
-- NOTE: This file is now managed by the migration system.
-- The actual schema is defined in src/db/migrations/*.sql files.
-- This file is kept for backward compatibility and documentation purposes.
--
-- To add new schema changes, create a new migration file in src/db/migrations/
-- with the naming convention: XXX_description.sql (e.g., 002_add_tags_table.sql)

-- Schema version tracking table is automatically created by the migration system
