export type ReactDiagnosticCodeV1 =
  | 'REACT_DYNAMIC_IMPORT_UNSUPPORTED'
  | 'REACT_DYNAMIC_COMPONENT_UNSUPPORTED'
  | 'REACT_SERVER_CLIENT_BOUNDARY_PARTIAL'
  | 'REACT_UNRESOLVED_BINDING'
  | 'REACT_AMBIGUOUS_BINDING';
